CREATE TABLE `observatoryReferences` (
	`id` int AUTO_INCREMENT NOT NULL,
	`createdByUserId` int NOT NULL,
	`title` varchar(240) NOT NULL,
	`creator` varchar(160) NOT NULL,
	`contentType` enum('post','carrossel','reel','copy') NOT NULL,
	`sourceKind` enum('upload','direct_media','published_post','copy') NOT NULL,
	`sourceUrl` text,
	`contentText` text NOT NULL,
	`mediaUrl` text,
	`mediaKey` varchar(1024),
	`mediaMimeType` varchar(120),
	`segmentHint` varchar(240) NOT NULL,
	`objectiveHint` varchar(240) NOT NULL,
	`metricsJson` text,
	`status` enum('processing','analyzed','needs_content','failed') NOT NULL DEFAULT 'processing',
	`classificationJson` text,
	`analysisJson` text,
	`promptVersion` varchar(32) NOT NULL DEFAULT '2.0',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `observatoryReferences_id` PRIMARY KEY(`id`),
	INDEX `observatoryReferences_createdAt_idx` (`createdAt`),
	INDEX `observatoryReferences_status_idx` (`status`),
	INDEX `observatoryReferences_contentType_idx` (`contentType`)
);

CREATE TABLE `observatoryPatterns` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(180) NOT NULL,
	`stage` enum('observation','hypothesis','provisional','validated','contradicted','obsolete') NOT NULL DEFAULT 'hypothesis',
	`creativeFamily` varchar(120) NOT NULL,
	`objective` varchar(160) NOT NULL,
	`segment` varchar(160) NOT NULL,
	`mechanism` text NOT NULL,
	`conditionsJson` text,
	`evidenceJson` text,
	`supportingCount` int NOT NULL DEFAULT 0,
	`counterexampleCount` int NOT NULL DEFAULT 0,
	`confidence` enum('low','medium','high') NOT NULL DEFAULT 'low',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `observatoryPatterns_id` PRIMARY KEY(`id`),
	INDEX `observatoryPatterns_stage_idx` (`stage`),
	INDEX `observatoryPatterns_family_idx` (`creativeFamily`)
);
