import { Badge } from "@/components/ui/badge";
import { trpc } from "@/lib/trpc";
import { ArrowRight, Clock3, Plus } from "lucide-react";
import { Link } from "wouter";

const statusMap = { completed: { label: "Concluída", className: "bg-emerald-50 text-emerald-700 border-emerald-100" }, processing: { label: "Em avaliação", className: "bg-amber-50 text-amber-700 border-amber-100" }, needs_content: { label: "Complemento necessário", className: "bg-amber-50 text-amber-800 border-amber-200" }, failed: { label: "Não concluída", className: "bg-rose-50 text-rose-700 border-rose-100" } } as const;

export default function History() {
  const { data: analyses = [], isLoading, error } = trpc.analyses.list.useQuery();
  return <div className="mx-auto max-w-6xl pb-10"><div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-violet-500">Biblioteca</p><h1 className="mt-1 font-display text-4xl font-extrabold tracking-[-0.06em] text-[#2b1058]">Histórico de avaliações</h1><p className="mt-2 text-sm text-slate-600">Consulte materiais enviados e retome qualquer relatório quando precisar.</p></div><Link href="/avaliar" className="inline-flex h-10 items-center rounded-md bg-[#2b1058] px-4 text-sm font-semibold text-white transition-colors hover:bg-[#39166e] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-violet-500"><Plus className="mr-2 h-4 w-4" />Nova avaliação</Link></div><div className="plateia-card overflow-hidden"><div className="grid grid-cols-[1.1fr_0.8fr_auto] gap-4 border-b border-violet-50 px-6 py-3 text-[11px] font-bold uppercase tracking-[0.12em] text-slate-400 sm:px-7"><span>Material</span><span>Data</span><span>Status</span></div>{error ? <div role="alert" className="p-8 text-sm text-rose-700">Não foi possível carregar o histórico agora. Atualize a página para tentar novamente.</div> : isLoading ? <div role="status" aria-busy="true" className="p-8 text-sm text-slate-500">Carregando histórico…</div> : analyses.length === 0 ? <div className="p-12 text-center"><Clock3 className="mx-auto mb-3 h-8 w-8 text-violet-300" /><p className="font-semibold text-[#2b1058]">Ainda não há avaliações.</p><p className="mt-1 text-sm text-slate-500">A sua biblioteca vai nascer após a primeira leitura.</p></div> : analyses.map(item => { const status = statusMap[item.status]; const score = item.reportJson ? JSON.parse(item.reportJson).synthesis?.overallScore : null; return <Link key={item.id} href={`/analises/${item.id}`}><div className="group grid cursor-pointer grid-cols-[1.1fr_0.8fr_auto] items-center gap-4 px-6 py-5 transition-colors hover:bg-violet-50/45 sm:px-7"><div className="min-w-0"><p className="truncate font-semibold text-[#2b1058]">{item.product || `Avaliação de ${item.contentType}`}</p><p className="mt-0.5 text-xs capitalize text-slate-500">{item.contentType}</p></div><span className="text-sm text-slate-500">{new Date(item.createdAt).toLocaleDateString("pt-BR")}</span><div className="flex items-center gap-2"><Badge variant="outline" className={status.className}>{status.label}</Badge>{score !== null && <span className="hidden text-sm font-extrabold text-[#2b1058] sm:inline">{score}</span>}<ArrowRight className="h-4 w-4 text-slate-300 group-hover:text-violet-600" /></div></div></Link>; })}</div></div>;
}
